### PR TITLE
Use webpack middleware in v3

### PR DESCRIPTION
**Pull request by bradleyboy**
This applies @adam-beck's work in #68 to the `next` branch to use webpack's middleware as per #65.

### CODE REVIEW

**Comment by kunchenguid** [comment]
i did something like this on 3.0.0-beta.2, changed a file, and then got this in the browser console:
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

did this happen to you as well?

for reference here are my files:

```javascript
// webpack config
var path = require('path')
var webpack = require('webpack')

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: {
    default: [
      'react-hot-loader/patch',
      'webpack-hot-middleware/client',
      path.join(__dirname, 'themes', 'default', 'index.js')
    ]
  },
  output: {
    path: path.join(__dirname, 'dist/'),
    filename: 'everything.[name].js',
    publicPath: '/'
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ],
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loaders: ['babel?presets[]=es2015,presets[]=react,presets[]=stage-0&plugins[]=react-hot-loader/babel']
    }, {
      test: /\.css$/,
      loader: 'style!css?modules&localIdentName=[name]---[local]---[hash:base64:5]'
    }]
  }
}
```

```javascript
// main part of server.js
  const compiler = webpack(WebpackDevConfig)

  app.use(WebpackDevMiddleware(compiler, {
    publicPath: WebpackDevConfig.output.publicPath,
    historyApiFallback: true,
    stats: {
      colors: true
    }
  }))
  app.use(WebpackHotMiddleware(compiler))

  app.get('*', renderHtml)
```

```javascript
// client side entry, i called this function from another file below
import 'babel-polyfill'
import React from 'react'
import { render } from 'react-dom'
import { applyMiddleware, combineReducers, createStore } from 'redux'
import { browserHistory } from 'react-router'
import { routerReducer, syncHistoryWithStore } from 'react-router-redux'
import Root from './root'
import thunkMiddleware from 'redux-thunk'
import reduxLogger from 'redux-logger'
import { AppContainer } from 'react-hot-loader'

module.exports = function (routes, reducers) {
  const createStoreWithMiddleware = applyMiddleware(
    thunkMiddleware,
    reduxLogger()
  )(createStore)

  const reducer = combineReducers(Object.assign({
    routing: routerReducer
  }, reducers))

  const store = createStoreWithMiddleware(reducer)
  const history = syncHistoryWithStore(browserHistory, store)

  render(
    <AppContainer>
      <Root history={history} routes={routes(store)} store={store} />
    </AppContainer>,
    document.getElementById('root')
  )

  if (module.hot) {
    module.hot.accept('./root', () => {
      const NewRoot = require('./root')
      render(
        <AppContainer>
          <NewRoot history={history} routes={routes(store)} store={store} />
        </AppContainer>,
        document.getElementById('root')
      )
    })
  }
}
```

```javascript
import React from 'react'
import setupClient from '../setup-client'
import { Route, Redirect } from 'react-router'
import Layout from './components/Layout'

const routes = (store) => {
  return (
    <Route path='/' component={Layout}>
      <Redirect from='*' to='/' />
    </Route>
  )
}

const reducers = {
  // key1: reducer1,
  // key2: reducer2
}

setupClient(routes, reducers)
```

**Comment by bradleyboy** [comment]
@kunchenguid Only thing that jumps out to me is this line:

```js
const NewRoot = require('./root')
```

I think that should be:

```js
const NewRoot = require('./root').default
```

**Comment by kunchenguid** [comment]
still getting the same thing... i'll dig in further

**Comment by kunchenguid** [comment]
do we need to do module.hot.accept() for every js file? i'm guessing module.hot.accept('./root', ...) is somehow not sufficient when i structured my files this way..

**Comment by kunchenguid** [comment]
this is my root.js

```javascript
import React from 'react'
import { Provider } from 'react-redux'
import { Router } from 'react-router'

module.exports = (props) => {
  return (
    <Provider store={props.store}>
      <Router history={props.history}>
        {props.routes}
      </Router>
    </Provider>
  )
}
```

the symptom we are seeing is that webpack can't figure out the file i'm editing is a dependent of this root.js. it might be because of i'm passing the children in dynamically through props.routes.

**Comment by muratozgul** [comment]
Any updates on this @kunchenguid? How did you solve it?

**Comment by dlebedynskyi** [comment]
@kunchenguid had the same problem. Try something like this 
```
if (process.env.NODE_ENV === 'development') {
  const AppContainer = require('react-hot-loader').AppContainer; //eslint-disable-line

  const render = () => {
// need to reload routes. 
    const routes = require('./app/routes').default(store); // eslint-disable-line no-shadow

    ReactDOM.render(
      <AppContainer>
        <Provider store={store}>
          <Router routes={routes} history={browserHistory}/>
        </Provider>
      </AppContainer>,
      rootEl);
  };

  render();

  // Hot reloading on the client. Need to reload routes for HRM to work
  if (module.hot) {
    module.hot.accept('./app/routes', render);
  }
}
```

**Comment by calesce** [comment]
Looks good, thanks! 👍

**Comment by elyobo** [comment]
@kunchenguid did you find a solution for your problem? @dlebedynskyi's suggestion doesn't resolve the issue for me.

**Comment by kunchenguid** [comment]
@elyobo sorry that was a long time ago.. i don't even remember what i had for breakfast.

**Comment by elyobo** [comment]
Ahahaha, fair enough.  I remember breakfast, but it was less than an hour ago, so ¯\_(ツ)_/¯

**Comment by dlebedynskyi** [comment]
@elyobo oh that was so old reply. worked at that time  ¯_(ツ)_/¯

**Comment by elyobo** [comment]
@dlebedynskyi actually, it _did_ end up working for me (more or less), it was just that I had an extra import in my entry point (unused, should have fixed my linting errors) that _also_ included the routes.  I removed that and suddenly it all worked, I guess the redundant import caused the update to come through as a different, unhandled path.

All good now :)

**Pull request merged**
