### PR TITLE
Use webpack-dev-middleware

### LINKED ISSUE #65: Use webpack-dev-middleware?
It’s got a nice syntax error overlay, and it was already fixed to work with Webpack 2.
We should probably use it here as well.

### PR DESCRIPTION
**Pull request by adam-beck**
Closes #65

### CODE REVIEW

**Comment by bradleyboy** [comment]
@adam-beck FYI - I walked through this and it works as expected, but `webpack-hot-middleware` needs to be added to package.json.

**Comment by adam-beck** [comment]
Hmm not sure how I missed that. I made the changes but don't know if I used the correct workflow to get these into Github. There is 2 commits with the same message now.

**Comment by pkese** [comment]
Hey @adam-beck,

Any chance you'd port this to version 3 as well?
I'm clueless about what what to include into webpack.config's `entry` array.

**Comment by bradleyboy** [comment]
@pkese I'm using this on v3, here's the entry:

```js
entry: [
  'react-hot-loader/patch',
  'webpack-hot-middleware/client',
  './src/index'
],
```

**Comment by iamyardem** [comment]
Hello @bradleyboy 

I've tried do like you wrote above but I receive error "[HMR] Hot Module Replacement is disabled." And nothing renders. I've checked bundle path, it can be resolved from index.html.

I've created repo with my non working code. If you have a chance to look at it, please help :)

Thanks!

https://github.com/iamyardem/react-redux-webpack-universal-app

**Comment by bradleyboy** [comment]
@iamyardem Nothing stands out to me, but your repo has changed quite a bit from the default. Here's a branch of v3 with middleware for reference: https://github.com/gaearon/react-hot-boilerplate/pull/72

**Comment by danmartinez101** [comment]
I'd vote in favor of not using the middleware over the dev-server. This PR adds a lot of green lines to the diff, but what does it do to better demonstrate hot-reloading?

**Comment by calesce** [comment]
Thanks!

**Pull request merged**
