### PR TITLE
add Routing

### PR DESCRIPTION
**Pull request by ir3ne**
I added a Router component with the exact path on App and a NotFound component in other paths.

### CODE REVIEW

**Comment by theKashey** [comment]
Does this sounds a bit obsolete? 
Half packages nowadays require React 16+ stuff, while this boilerplate still uses 0.14

**Comment by ir3ne** [comment]
@theKashey  Yes you're right, it's a React obsolete version. I'm studying and I would like to ask to you if do you think the router solution is also obsolete. 
Thanks

**Comment by theKashey** [comment]
react-router v4 is quite modern, but as long nobody tests their libraries agains React v14 - everything (probably) would be broken.

**Comment by ir3ne** [comment]
ok I understand. Thank you :)

**Pull request closed without merging**
